# Name of the workflow
name: deploy

# when the workflow should run
on: #trigger
  push: #whenever code is pushed to github the workflow automatically runs 
  workflow_call: #whenever this workflow to be called from another workflow
  workflow_dispatch: #whenever you want the workflow to be called manually
  schedule: #whenever you want the workflow to run at a specific time
    - 
# jobs in the workflow
jobs:
  build:
    runs-on: ubuntu-latest
    # steps in the workflow
    steps:
      - name: Deploy the code
        run: echo "Code deployed to AWS EC2 instance"
